Fix contact info & various texts
ANGIstudio/goodplace-landingspagina pull request #28
Opened 2022-11-03 12:51 UTC by jeremy-goodplace

2022-11-04 08:32 UTC, dominiquemaria commented on src/data/data.ts
> +    href: 'https://www.facebook.com/goodplacefoundation/',
https://www.facebook.com/profile.php?id=100078787633106

2022-11-04 08:34 UTC, dominiquemaria requested changes
Added correct Facebook link in comments, other than that looks good to me

2022-11-04 09:26 UTC, jeremy-goodplace commented on src/data/data.ts
> +    href: 'https://www.facebook.com/goodplacefoundation/',
Thanks, fixed!

2022-11-06 16:15 UTC, dominiquemaria approved these changes

2022-11-06 16:16 UTC, merged